{% set name = "ChemDataExtractor" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c989cfb60048dc57a49472228381574bff351c31896bdcd621991f68c0f9cc9

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - cde = chemdataextractor.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - appdirs
    - beautifulsoup4
    - click
    - cssselect
    - dawg
    - lxml
    - nltk
    - pdfminer.six
    - python-crfsuite
    - python-dateutil
    - pyyaml
    - requests
    - six

test:
  requires:
    - python {{ python_min }}
  commands:
    - cde
  imports:
    - chemdataextractor
    - chemdataextractor.biblio
    - chemdataextractor.cli
    - chemdataextractor.doc
    - chemdataextractor.nlp
    - chemdataextractor.parse
    - chemdataextractor.reader
    - chemdataextractor.scrape
    - chemdataextractor.text

about:
  home: http://chemdataextractor.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatically extract chemical information from scientific documents.
  doc_url: http://chemdataextractor.org/docs
  dev_url: https://github.com/mcs07/ChemDataExtractor

extra:
  recipe-maintainers:
    - mcs07
